"""Add purchase_price to items table

Revision ID: 01178976a702
Revises: 34327a25e95f
Create Date: 2025-07-13 07:35:52.568685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01178976a702'
down_revision: Union[str, None] = '34327a25e95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The purchase_price column already exists, we need to alter it to make it nullable
    op.alter_column('items', 'purchase_price',
                    existing_type=sa.Numeric(precision=10, scale=2),
                    nullable=True,
                    comment='Purchase price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert to NOT NULL constraint
    op.alter_column('items', 'purchase_price',
                    existing_type=sa.Numeric(precision=10, scale=2),
                    nullable=False,
                    comment=None)
    # ### end Alembic commands ###