"""Remove rental module tables

Revision ID: 92796f60a259
Revises: 51e65ebde28e
Create Date: 2025-07-17 08:38:59.740065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92796f60a259'
down_revision: Union[str, None] = '51e65ebde28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop rental module tables only
    op.drop_index('idx_rental_return_line_damage_level', table_name='rental_return_lines')
    op.drop_index('idx_rental_return_line_inventory_unit', table_name='rental_return_lines')
    op.drop_index('idx_rental_return_line_return', table_name='rental_return_lines')
    op.drop_index('idx_rental_return_line_status', table_name='rental_return_lines')
    op.drop_index('ix_rental_return_lines_is_active', table_name='rental_return_lines')
    op.drop_table('rental_return_lines')
    
    op.drop_index('idx_inspection_report_damage_level', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_date', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_inspected_by', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_inventory_unit', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_return', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_status', table_name='inspection_reports')
    op.drop_index('ix_inspection_reports_is_active', table_name='inspection_reports')
    op.drop_table('inspection_reports')
    
    op.drop_index('idx_rental_return_date', table_name='rental_returns')
    op.drop_index('idx_rental_return_expected_date', table_name='rental_returns')
    op.drop_index('idx_rental_return_location', table_name='rental_returns')
    op.drop_index('idx_rental_return_processed_by', table_name='rental_returns')
    op.drop_index('idx_rental_return_status', table_name='rental_returns')
    op.drop_index('idx_rental_return_transaction', table_name='rental_returns')
    op.drop_index('idx_rental_return_type', table_name='rental_returns')
    op.drop_index('ix_rental_returns_is_active', table_name='rental_returns')
    op.drop_table('rental_returns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: This migration removes obsolete tables. Downgrading would recreate them,
    # but the rental functionality has been moved to the transaction module.
    pass
    # ### end Alembic commands ###