"""Add foreign key constraints for inventory_unit relationships

Revision ID: b3e6b7fb5e6c
Revises: 20a06314dac0
Create Date: 2025-07-10 23:11:23.202843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e6b7fb5e6c'
down_revision: Union[str, None] = '20a06314dac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###