"""Add SKU field to items and create SKUSequence table

Revision ID: daeaa928ca43
Revises: 35731cf5b33f
Create Date: 2025-07-11 22:28:27.575898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daeaa928ca43'
down_revision: Union[str, None] = '35731cf5b33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add SKU field to items table (initially nullable for existing items)
    op.add_column('items', sa.Column('sku', sa.String(length=50), nullable=True, comment='Stock Keeping Unit'))
    
    # Create indexes for SKU field
    op.create_index('idx_item_sku', 'items', ['sku'], unique=False)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop SKU indexes
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index('idx_item_sku', table_name='items')
    
    # Drop SKU field from items table
    op.drop_column('items', 'sku')
    # ### end Alembic commands ###